Autologin Feature Added
butlerx/wetty pull request #122
Opened 2018-06-22 10:31 UTC by koushikmln

Login by passing username and password in url as query parameters. 
Migrated to node-pty which is currently maintained and updated. 
added feature to put in global username and password
Added server keep alive in ssh options to keep the session alive.

2018-11-07 20:43 UTC, butlerx commented
Could you rebase also quite a few users run this in docker so that would be a requirement

2018-11-22 10:18 UTC, koushikmln commented
What is the exact issue you are facing on docker? Can you give me some logs if possible? I will also try setting up and try it out.

2018-11-22 20:35 UTC, koushikmln commented
@butlerx added docker compatibility and rebased code.

2018-11-22 21:01 UTC, butlerx requested changes

2018-11-22 21:01 UTC, butlerx commented on public/wetty/index.html
> +    <script src="/wetty/hterm_all.js"></script>
this shouldn't be required it should be bundled in `wetty.js`

2018-11-22 21:01 UTC, butlerx commented on public/wetty/index.html
> +    <script src="/wetty/wetty.js"></script>
this is required at the bottom of the file

2018-11-22 21:04 UTC, koushikmln commented
My bad. Fixed it.

2018-11-22 21:17 UTC, merged

2018-11-22 21:18 UTC, butlerx commented
thanks for that

2018-11-22 22:47 UTC, koushikmln commented
Let me know if you have some features in mind. We can discuss on email and collaborate.