Better Configuration UX
butlerx/wetty pull request #342
Opened 2021-06-05 02:30 UTC by Christian7573

I plan on embedding wetty in a project of mine and looked into changing the color theme. While the previous editor allowed changing the color theme, it was very clunky to use, needing to ready XTerm documentation to find property names and then painfully edit a tiny JSON window on my phone. I've replaced it with a simple field-value editor and copied over all of the options listed in XTerm's documentation. It looks like you have this project set up in a very specific way, so I've done my best to keep it isolated in the assets folder using vanilla HTML, CSS, and JS.

- Replaced the JSON editor with a field-value GUI.
- Modified the loading, saving, and application of XTerm configuration.
- Old options strings will be converted to { xterm: old_options } upon using the new version.
- Added the option to disable the XTerm Fit plugin if people choose to manually specify rows and columns.
- Changed sizing of configuration editor to better work with smaller and mobile screens.
- Bumped version of @typescript/eslint-plugin; NPM could not resolve the version previously listed in package.json.
- Added package-lock.json and yarn.lock to the .gitignore.
- Expose the Term object as window.wetty_term; Not related to this PR, but I'll be using it to access the terminal externally for my project.

2021-07-20 08:17 UTC, butlerx requested changes

2021-07-20 08:17 UTC, butlerx commented on .gitignore
> +/yarn.lock
Lock files shouldn't be in the git ignore

2021-08-25 16:10 UTC, Christian7573 commented
Interesting to note: eslint 2.5.0 is no longer available from npm and only available through yarn.
Let me know if you'd like me to squash commits.

2021-08-25 16:26 UTC, butlerx reviewed
I'm curious to know the reasoning behind using an iframe rather than adding to the main page?

2021-08-25 16:26 UTC, butlerx commented on src/client/wetty/term/confiruragtion/load.ts
> +export function loadOptions(): any {
Why switch from `object` to `any`?

2021-08-26 01:49 UTC, Christian7573 commented on src/client/wetty/term/confiruragtion/load.ts
> +export function loadOptions(): any {
I believe TS didn't like me indexing/using properties from type object, however changing it back to object now does not bring that error up. Will revert.

2021-08-26 02:00 UTC, Christian7573 commented
> I'm curious to know the reasoning behind using an iframe rather than adding to the main page?

To have a hard boundary for CSS and JS since it's neither using SCSS nor bundled TS.

2021-08-26 09:10 UTC, merged